FROM nvidia/opengl:1.0-glvnd-devel-ubuntu18.04

# Note: this Dockerfile needs to be used with nvidia-docker
# Note: needs nvidia/opengl. nvidia/cuda does not support opengl
MAINTAINER Yuxin Wu

# make apt-get noninteractive
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y \
	libglm-dev libx11-dev libegl1-mesa-dev \
	libpng-dev xorg-dev cmake libjpeg-dev python3-opencv \
	python3-dev build-essential pkg-config git curl wget automake libtool

RUN git clone https://github.com/glfw/glfw.git && cd glfw && mkdir build && cd build && cmake .. && make &&  make install && ldconfig
RUN curl -fSsL -O https://bootstrap.pypa.io/get-pip.py && \
	python3 get-pip.py && \
	rm get-pip.py
# tqdm is only used by the tests
RUN pip3 install tqdm
